### ISSUE TITLE
Python anaconda install conflicting with git/gettext

### ISSUE THREAD

**Issue by mariusbutuc** [danhper/asdf-python#44]
Hey guys, installed Anaconda3 v5.3.0 like so

```sh
$ asdf install python anaconda3-5.3.0
```

and it seems that something is in conflict with gettext/git now. 

## What is the experienced (undesired) behaviour?

```sh
$ git pull
GNU gettext shell script function library version 0.19.8.1
Usage: . gettext.sh
```

### With `python anaconda3-5.3.0`

```sh
$ which gettext
~/.asdf/shims/gettext
```

where

```
$ cat ~/.asdf/shims/gettext
#!/usr/bin/env bash
# asdf-plugin: python
# asdf-plugin-version: anaconda3-5.3.0
exec /usr/local/opt/asdf/libexec/private/asdf-exec python bin/gettext "$@"
```

and 

```sh
$ ls -al ~/.asdf/shims | wc -l
     415
```

While after uninstalling it…

```sh
$ asdf uninstall python anaconda3-5.3.0
```

### Without `python anaconda3-5.3.0`

```sh
$ git pull
Current branch master is up to date.
```

🎉, and FWIW, there are _far_ fewer shims now.

```sh
$ ls -al ~/.asdf/shims | wc -l
      31
```
___

Honestly, I don't even know if this is the right place to ask this question versus this being an `asdf` issue, or python, or anaconda, or something completely different?

I'm open to getting help on debugging this further, or being guided to a better place to ask this, or anything else. Thanks in advance! :v:

___

<details>
<summary>
PS: Context folded below
</summary>
I'm running macOS with git 2.19.1

```sh
$ sw_vers -productVersion
10.13.6

$ git --version
git version 2.19.1
```
</details>

**Comment by mariusbutuc** [comment]
## Update / fix / workaround: 

Upon digging deeper `gettext` is installed on my machine via homebrew. 

In it's info, there was a hint at the "solution":

```sh
$ brew info gettext
gettext: stable 0.19.8.1 (bottled) [keg-only]
GNU internationalization (i18n) and localization (l10n) library
https://www.gnu.org/software/gettext/
/usr/local/Cellar/gettext/0.19.8.1 (1,934 files, 16.9MB)
  Poured from bottle on 2017-01-16 at 20:56:16
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gettext.rb
==> Caveats
gettext is keg-only, which means it was not symlinked into /usr/local,
because macOS provides the BSD gettext library & some software gets confused if both are in the library path.

If you need to have gettext first in your PATH run:
  echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> ~/.bash_profile

# …snip…
```

The last bit is the relevant one: changing `~/.bash_profile` to have gettext first in the `PATH` "fixed".

**Comment by diimdeep** [comment]
Exactly the same issue for me https://github.com/asdf-vm/asdf/issues/693

**Comment by oolonc** [comment]
Same issue for me using plugin Python mambaforge. Installing `matplotlib` pulls down `gettext`, conflicting with the system version. Uninstalling fixes things. 

```
Removing specs: ['gettext']
Transaction

  Prefix: /home/axel/.asdf/installs/python/mambaforge

  Removing specs:

   - gettext


  Package              Version  Build               Channel       Size
────────────────────────────────────────────────────────────────────────
  Remove:
────────────────────────────────────────────────────────────────────────

  - alsa-lib             1.2.3  h516909a_0          installed
  - dbus                1.13.6  h48d8840_2          installed
  - expat                2.4.1  h9c3ff4c_0          installed
  - fontconfig          2.13.1  hba837de_1005       installed
  - gettext           0.19.8.1  h0b5b191_1005       installed
  - glib                2.68.4  h9c3ff4c_0          installed
  - glib-tools          2.68.4  h9c3ff4c_0          installed
  - gst-plugins-base    1.18.4  hf529b03_2          installed
  - gstreamer           1.18.4  h76c114f_2          installed
  - libclang            11.1.0  default_ha53f305_1  installed
  - libevent            2.1.10  hcdb4288_3          installed
  - libglib             2.68.4  h3e27bee_0          installed
  - libllvm11           11.1.0  hf817b99_2          installed
  - libogg               1.3.4  h7f98852_1          installed
  - libopus              1.3.1  h7f98852_1          installed
  - libpq                 13.3  hd57d9b9_0          installed
  - libuuid             2.32.1  h7f98852_1000       installed
  - libvorbis            1.3.7  h9c3ff4c_0          installed
  - libxcb                1.13  h7f98852_1003       installed
  - libxkbcommon         1.0.3  he3ba5ed_0          installed
  - matplotlib           3.4.3  py39hf3d152e_0      installed
  - mysql-common        8.0.25  ha770c72_2          installed
  - mysql-libs          8.0.25  hfa10184_2          installed
  - nspr                  4.30  h9c3ff4c_0          installed
  - nss                   3.69  hb5efdd6_0          installed
  - pcre                  8.45  h9c3ff4c_0          installed
  - pthread-stubs          0.4  h36c2ea0_1001       installed
  - pyqt                5.12.3  py39hf3d152e_7      installed
  - pyqt-impl           5.12.3  py39h0fcd23e_7      installed
  - pyqt5-sip          4.19.18  py39he80948d_7      installed
  - pyqtchart             5.12  py39h0fcd23e_7      installed
  - pyqtwebengine       5.12.1  py39h0fcd23e_7      installed
  - qt                  5.12.9  hda022c4_4          installed
  - xorg-libxau          1.0.9  h7f98852_0          installed
  - xorg-libxdmcp        1.1.3  h7f98852_0          installed

  Summary:

  Remove: 35 packages

  Total download: 0  B

────────────────────────────────────────────────────────────────────────

```
